# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: sglang-agg
spec:
  services:
    Frontend:
      dynamoNamespace: sglang-agg
      componentType: frontend
      replicas: 1 # overridden by workflow if FRONTEND_REPLICAS provided
      extraPodSpec:
        mainContainer:
          image: $MAIN_CONTAINER_IMAGE # default my-registry/sglang-runtime:my-tag
    decode:
      envFromSecret: hf-token-secret
      dynamoNamespace: sglang-agg
      componentType: worker
      replicas: 1 # overridden by workflow if DECODE_REPLICAS provided
      resources:
        limits:
          gpu: "${DECODE_GPUS}" # default 1 GPUs per decode worker
      extraPodSpec:
        mainContainer:
          image: $MAIN_CONTAINER_IMAGE # default my-registry/sglang-runtime:my-tag
          workingDir: /workspace/components/backends/sglang
          command:
            - /bin/sh
            - -c
          args:
            - "$DECODE_COMMAND" # constructed by workflow (includes model $MODEL, page size ${PAGE_SIZE}, parallel flags)

