# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: sglang-disagg-multinode
spec:
  envs:
  - name: HF_TOKEN
    valueFrom:
      secretKeyRef:
        name: hf-token-secret
        key: HF_TOKEN
  - name: GLOO_SOCKET_IFNAME
    value: "eth0"
  backendFramework: sglang
  services:
    Frontend:
      dynamoNamespace: sglang-disagg-multinode
      componentType: frontend
      replicas: 1 # overridden by workflow if FRONTEND_REPLICAS provided
      extraPodSpec:
        mainContainer:
          image: $MAIN_CONTAINER_IMAGE
    decode:
      multinode:
        nodeCount: ${MULTINODE_DECODE_NODE_COUNT}
      envFromSecret: hf-token-secret
      dynamoNamespace: sglang-disagg-multinode
      componentType: worker
      replicas: 1 # overridden by workflow if DECODE_REPLICAS provided
      resources:
        limits:
          gpu: "${DECODE_GPUS}" # per decode pod
      extraPodSpec:
        mainContainer:
          image: $MAIN_CONTAINER_IMAGE
          workingDir: /workspace/components/backends/sglang
          command:
            - /bin/sh
            - -c
          args:
            - "$DECODE_COMMAND"
    prefill:
      multinode:
        nodeCount: ${MULTINODE_PREFILL_NODE_COUNT}
      envFromSecret: hf-token-secret
      dynamoNamespace: sglang-disagg-multinode
      componentType: worker
      replicas: 1 # overridden by workflow if PREFILL_REPLICAS provided
      resources:
        limits:
          gpu: "${PREFILL_GPUS}" # per prefill pod
      extraPodSpec:
        mainContainer:
          image: $MAIN_CONTAINER_IMAGE
          workingDir: /workspace/components/backends/sglang
          command:
            - /bin/sh
            - -c
          args:
            - "$PREFILL_COMMAND"
