# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: sglang-disagg
spec:
  services:
    Frontend:
      dynamoNamespace: sglang-disagg
      componentType: frontend
      replicas: 1 # overridden by workflow if FRONTEND_REPLICAS provided
      extraPodSpec:
        mainContainer:
          image: $MAIN_CONTAINER_IMAGE
    decode:
      envFromSecret: hf-token-secret
      dynamoNamespace: sglang-disagg
      componentType: worker
      replicas: 1 # overridden by workflow if DECODE_REPLICAS provided
      resources:
        limits:
          gpu: "${DECODE_GPUS}" # default 1
      extraPodSpec:
        mainContainer:
          image: $MAIN_CONTAINER_IMAGE
          workingDir: /workspace/components/backends/sglang
          command:
            - /bin/sh
            - -c
          args:
            - "$DECODE_COMMAND"

    prefill:
      envFromSecret: hf-token-secret
      dynamoNamespace: sglang-disagg
      componentType: worker
      replicas: 1 # overridden by workflow if PREFILL_REPLICAS provided
      resources:
        limits:
          gpu: "${PREFILL_GPUS}" # default 1
      extraPodSpec:
        mainContainer:
          image: $MAIN_CONTAINER_IMAGE
          workingDir: /workspace/components/backends/sglang
          command:
            - /bin/sh
            - -c
          args:
            - "$PREFILL_COMMAND"
